function ACPR_values = compute_acpr(input_signal, fs, bw_main_ch, nperseg)
    % signal = signal(:);
    signal = input_signal(:,1) + 1i * input_signal(:,2);
    fs = 800e6;
    bw_main_ch = 200e6;
    sub_ch = 300e6
    N_fft = 2560;
    
    hACPR = comm.ACPR('SampleRate', fs, ...
                      'PowerUnits', 'dBW', ...
                      'MainChannelFrequency', 0, ...
                      'MainMeasurementBandwidth', bw_main_ch, ...
                      'AdjacentChannelOffset', [-sub_ch, sub_ch], ...
                      'AdjacentMeasurementBandwidth', bw_main_ch, ...
                      'MainChannelPowerOutputPort', true, ...
                      'AdjacentChannelPowerOutputPort', true, ...
                      'SpectralEstimation', 'Specify window parameters', ...
                      'SegmentLength', N_fft, ...
                      'OverlapPercentage', 60, ...
                      'Window', 'Blackman-Harris', ...
                      'FFTLength', 'Custom', ...
                      'CustomFFTLength', N_fft);
    ACPR_values = hACPR(signal);
end

