function [acpr_left, acpr_right] = compute_acpr(signal, fs, bw_main_ch, nperseg)
    signal = signal(:);
    % fs = 800e6;
    % bw_main_ch = 200e6;
    % N_fft = 2560;
    N_fft = nperseg;
    
    hACPR = comm.ACPR('SampleRate', fs, ...
                      'PowerUnits', 'dBW', ...
                      'MainChannelFrequency', 0, ...
                      'MainMeasurementBandwidth', bw_main_ch, ...
                      'AdjacentChannelOffset', [-bw_main_ch, bw_main_ch], ...
                      'AdjacentMeasurementBandwidth', bw_main_ch, ...
                      'MainChannelPowerOutputPort', true, ...
                      'AdjacentChannelPowerOutputPort', true, ...
                      'SpectralEstimation', 'Specify window parameters', ...
                      'SegmentLength', N_fft, ...
                      'OverlapPercentage', 60, ...
                      'Window', 'Blackman-Harris', ...
                      'FFTLength', 'Custom', ...
                      'CustomFFTLength', N_fft);
    ACPR_values = hACPR(signal);
    acpr_left = ACPR_values(1);
    acpr_right = ACPR_values(2);
end

